server:
  port: 8085
spring:
  application:
    name: showlive
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/showlive?useSSL=false&serverTimezone=UTC
    username: root
    password: ayb20010107
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: sylybimike@163.com
    #授权码
    password: Ayb45937736
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


mybatis-plus:
  type-aliases-package: com.ayb.entity # 别名扫描包
#logging:
#  level:
#    com.hmdp: debug
