---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2024/6/6 11:21
---
--- 参数
--- 优惠券ID
local ticketID = ARGV[1]
--- 用户ID数组，以逗号分隔的字符串形式
local userIDs = ARGV[2]

---
local stockKey = 'ticket:stock:' .. ticketID
local orderKey = 'ticket:order:' .. ticketID

--- 把传进来的以逗号分隔的身份证字符串转化为lua表类型
local userIDList = {}
for userID in string.gmatch(userIDs, '([^,]+)') do
    table.insert(userIDList, userID)
end

--- 查询库存
local stock = tonumber(redis.call('get', stockKey))
--- 如果库存不足 返回1
if stock <= 0 then
    return 1
end


--- 遍历表，只要有一个已经买过票的，此单全部返回fail
for _, userID in ipairs(userIDList) do
    if redis.call('sismember', orderKey, userID) == 1 then
        return 2
    end
end

--- 记录购票人身份证号
for _, userID in ipairs(userIDList) do
    redis.call('sadd', orderKey, userID)
end

--- 扣库存
redis.call('incrby', stockKey, -#userIDList)

return 0
